typography_spectrum: 0.6502677609678358
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.09124902985058725
  lightness: 0.547944586025551
  saturation: 0.5899885226972401
  rhythmicContrast: 0.8770355351734906
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.04584066825918853
analytics:
  google: null
  facebook: null
  twitter: null
name: Jessica Ice
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Jacobs University Foundation of America
    id: 66b841ac-53d9-497a-960b-cf9f8db9e44c
    type: content
  - name: Home
    id: 746b71d1-7c4d-4ac6-86b3-d2e9ba84b514
    type: content
favicon: null
title: Jessica Ice
purpose: []
